__default__:
    partition: norm
    threads: 4
    mem: 16g
    time: '2-00:00:00'
    gres: 'lscratch:50'

Merge1:
    partition: norm
    threads: 4
    mem: 8g
    time: '2-00:00:00'
    gres: 'lscratch:10'

Merge2:
    partition: norm
    threads: 4
    mem: 8g
    time: '2-00:00:00'
    gres: 'lscratch:10'

Fastp:
    partition: norm
    threads: 8
    mem: 16g
    time: '2-00:00:00'
    gres: 'lscratch:100'

Duplex:
    partition: norm
    threads: 16
    mem: 64g
    time: '2-00:00:00'
    gres: 'lscratch:100'

Multiqc:
    partition: norm
    threads: 8
    mem: 16g
    time: '2-00:00:00'
    gres: 'lscratch:100'

Merge_summary:
    partition: norm
    threads: 8
    mem: 16g
    time: '2-00:00:00'
    gres: 'lscratch:100'